(eval-when-compile    (require 'color-theme))
(defun color-theme-infinity ()
  "Color theme by Siddhartha Reddy, created 2011-04-29."
  (interactive)
  (color-theme-install
   '(color-theme-infinity
     ((background-color . "#1a1a1c")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "orange")
      (foreground-color . "#F8F8F8")
      (mouse-color . "sienna1"))
     ((apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (cua-global-mark-cursor-color . "cyan")
      (cua-normal-cursor-color . "red")
      (cua-overwrite-cursor-color . "yellow")
      (cua-read-only-cursor-color . "darkgreen")
      (hl-line-face . hl-line)
      (ispell-highlight-face . isearch)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (ns-use-system-highlight-color . t)
      (org-goto-interface . outline)
      (view-highlight-face . highlight)
      (viper-replace-overlay-cursor-color . "red4")
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "apple" :family "DejaVu_Sans_Mono"))))
     (aquamacs-variable-width ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Lucida Grande"))))
     (autoface-default ((t (:family "DejaVu_Sans_Mono" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F8" :background "#1a1a1c" :stipple nil :height 110))))
     (better-fringes-bitmap ((t (:foreground "dark khaki"))))
     (better-fringes-important-bitmap ((t (:foreground "red"))))
     (blank-newline ((t (:foreground "lightgrey" :weight normal))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "#9B703F"))))
     (border ((t (:background "black"))))
     (border-glyph ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (buffers-tab ((t (:background "#141414" :foreground "#CACACA"))))
     (button ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "yellow"))))
     (compilation-column-number ((t (:foreground "#9B703F"))))
     (compilation-error ((t (:foreground "red" :background "#EE799F"))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:foreground "#7587A6"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (:family "DejaVu_Sans_Mono" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F8" :background "#1a1a1c" :stipple nil :height 110))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "orange"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:underline nil :foreground "magenta4"))))
     (custom-button-unraised ((t (:underline nil))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "gray85"))))
     (custom-comment-tag ((t (:foreground "blue4"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :weight bold :foreground "blue1"))))
     (custom-group-tag ((t (:bold t :family "Sans Serif" :foreground "blue1" :weight bold :height 1.2))))
     (custom-group-tag-1 ((t (:bold t :family "Sans Serif" :foreground "red1" :weight bold :height 1.2))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:underline t :foreground "blue1"))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "dark green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "blue1" :weight bold))))
     (custom-visibility ((t (:underline t :foreground "blue1" :height 0.8))))
     (dired-directory ((t (:foreground "#9B703F"))))
     (dired-flagged ((t (:foreground "red" :background "#EE799F"))))
     (dired-header ((t (:foreground "#9B703F"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:foreground "#CF6A4C"))))
     (dired-marked ((t (:foreground "red" :background "#EE799F"))))
     (dired-perm-write ((t (:foreground "#5F5A60"))))
     (dired-symlink ((t (:foreground "#CDA869"))))
     (dired-warning ((t (:foreground "red" :background "#EE799F"))))
     (echo-area ((t (:stipple nil :strike-through nil :underline nil :slant normal :weight normal :width normal :family "Lucida Grande"))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (escape-glyph ((t (:foreground "brown"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "LightPink"))))
     (flymake-warnline ((t (:background "LightBlue2"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "#CACACA"))))
     (font-lock-comment-delimiter-face ((t (:foreground "#5F5A60"))))
     (font-lock-comment-face ((t (:foreground "#5F5A60"))))
     (font-lock-constant-face ((t (:foreground "#CF6A4C"))))
     (font-lock-doc-face ((t (:foreground "#8F9D6A"))))
     (font-lock-doc-string-face ((t (:foreground "DarkOrange"))))
     (font-lock-function-name-face ((t (:foreground "#9B703F"))))
     (font-lock-keyword-face ((t (:foreground "#CDA869"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
     (font-lock-reference-face ((t (:foreground "SlateBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "#E9C062"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "red"))))
     (font-lock-string-face ((t (:foreground "#8F9D6A"))))
     (font-lock-type-face ((t (:foreground "#9B703F"))))
     (font-lock-variable-name-face ((t (:foreground "#7587A6"))))
     (font-lock-warning-face ((t (:background "#EE799F" :foreground "red"))))
     (fringe ((t (:foreground "grey55"))))
     (fundamental-mode-default ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "DejaVu_Sans_Mono" :height 110))))
     (gui-element ((t (:background "#D4D0C8" :foreground "black"))))
     (header-line ((t (:width normal :weight normal :slant normal :underline nil :strike-through nil :box (:line-width 3 :color "#0a0a0c") :stipple nil :strike-through nil :underline nil :family "Lucida Grande" :background "grey90" :foreground "grey20" :box nil :height 120))))
     (help-argument-name ((t (:italic t :slant italic))))
     (hi-black-b ((t (:bold t :weight bold))))
     (hi-black-hb ((t (:bold t :family "Sans Serif" :weight bold :height 1.67))))
     (hi-blue ((t (:background "light blue"))))
     (hi-blue-b ((t (:bold t :foreground "blue1" :weight bold))))
     (hi-green ((t (:background "green1"))))
     (hi-green-b ((t (:bold t :foreground "green1" :weight bold))))
     (hi-mumamo-black-b ((t (:bold t :underline t :weight bold))))
     (hi-mumamo-blue ((t (:underline "light blue"))))
     (hi-mumamo-blue-b ((t (:bold t :underline "blue1" :weight bold))))
     (hi-mumamo-green ((t (:underline "green1"))))
     (hi-mumamo-green-b ((t (:bold t :underline "green1" :weight bold))))
     (hi-mumamo-pink ((t (:underline "pink"))))
     (hi-mumamo-red-b ((t (:bold t :underline "red1" :weight bold))))
     (hi-mumamo-yellow ((t (:underline "yellow1"))))
     (hi-pink ((t (:background "pink"))))
     (hi-red-b ((t (:bold t :foreground "red1" :weight bold))))
     (hi-yellow ((t (:background "yellow1"))))
     (highlight ((t (:background "#111111"))))
     (highlight-symbol-face ((t (:background "#3a3a3c"))))
     (highline-face ((t (:background "SeaGreen"))))
     (hl-line ((t (:background "#0a0a0c"))))
     (ido-first-match ((t (:foreground "#8F9D6A"))))
     (ido-incomplete-regexp ((t (:foreground "red" :background "#EE799F"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "#8F9D6A"))))
     (ido-subdir ((t (:foreground "#CF6A4C"))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:italic t :slant italic))))
     (latex-mode-default ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 130 :width normal :family "Lucida Grande"))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (left-margin ((t (nil))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (nil))))
     (minibuffer ((t (:family "Lucida Grande" :width normal :weight normal :slant normal :underline nil :strike-through nil :stipple nil))))
     (minibuffer-prompt ((t (:foreground "yellow"))))
     (mlinks-font-lock-face ((t (:underline t :foreground "blue1"))))
     (mlinks-hyperactive-link-face ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (mlinks-link-face ((t (:background "#111111"))))
     (mode-line ((t (:family "Lucida Grande" :underline nil :strike-through nil :stipple nil :background "#0a0a0c" :foreground "#a0a0c0" :box (:line-width 3 :color "#0a0a0c") :strike-through nil :underline nil :slant normal :weight normal :width normal :height 120))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-flags ((t (:family "Monaco"))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:family "Lucida Grande" :underline nil :strike-through nil :stipple nil :background "#2a2a2c" :foreground "#a2a2c2" :box nil :strike-through nil :underline nil :slant normal :weight normal :width normal :height 120))))
     (mouse ((t (:background "sienna1"))))
     (mumamo-background-chunk-major ((t (:background "cornsilk"))))
     (mumamo-background-chunk-submode ((t (:background "#222222"))))
     (mumamo-background-chunk-submode1 ((t (:background "Azure"))))
     (mumamo-background-chunk-submode2 ((t (:background "#e6ff96"))))
     (mumamo-background-chunk-submode3 ((t (:background "#f7d1f4"))))
     (mumamo-background-chunk-submode4 ((t (:background "orange"))))
     (mumamo-border-face-in ((t (:foreground "SeaGreen" :underline nil :slant normal :weight normal))))
     (mumamo-border-face-out ((t (:foreground "SeaGreen" :underline nil :slant normal :weight normal))))
     (next-error ((t (:background "#27292A"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (notify-user-of-mode ((t (:foreground "dark blue"))))
     (ns-working-text-face ((t (:underline t))))
     (nxml-attribute-colon ((t (nil))))
     (nxml-attribute-local-name ((t (:foreground "#7587A6"))))
     (nxml-attribute-prefix ((t (:foreground "#CACACA"))))
     (nxml-attribute-value ((t (:foreground "#8F9D6A"))))
     (nxml-attribute-value-delimiter ((t (:foreground "#8F9D6A"))))
     (nxml-cdata-section-CDATA ((t (:foreground "#CACACA"))))
     (nxml-cdata-section-content ((t (nil))))
     (nxml-cdata-section-delimiter ((t (nil))))
     (nxml-char-ref-delimiter ((t (:foreground "#CF6A4C"))))
     (nxml-char-ref-number ((t (:foreground "#CF6A4C"))))
     (nxml-comment-content ((t (:foreground "#5F5A60"))))
     (nxml-comment-delimiter ((t (:foreground "#5F5A60"))))
     (nxml-delimited-data ((t (:foreground "#8F9D6A"))))
     (nxml-delimiter ((t (nil))))
     (nxml-element-colon ((t (nil))))
     (nxml-element-local-name ((t (:foreground "#9B703F"))))
     (nxml-element-prefix ((t (:foreground "#CACACA"))))
     (nxml-entity-ref-delimiter ((t (:foreground "#CF6A4C"))))
     (nxml-entity-ref-name ((t (:foreground "#CF6A4C"))))
     (nxml-glyph ((t (:background "light grey" :foreground "black" :slant normal :weight normal))))
     (nxml-hash ((t (:foreground "#CACACA"))))
     (nxml-heading ((t (:bold t :weight bold))))
     (nxml-markup-declaration-delimiter ((t (nil))))
     (nxml-name ((t (:foreground "#CACACA"))))
     (nxml-namespace-attribute-colon ((t (nil))))
     (nxml-namespace-attribute-prefix ((t (:foreground "#7587A6"))))
     (nxml-namespace-attribute-value ((t (:foreground "#8F9D6A"))))
     (nxml-namespace-attribute-value-delimiter ((t (:foreground "#8F9D6A"))))
     (nxml-namespace-attribute-xmlns ((t (:foreground "#CACACA"))))
     (nxml-outline-active-indicator ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :width normal :foundry "apple" :family "DejaVu_Sans_Mono" :box 1 :height 110))))
     (nxml-outline-ellipsis ((t (:bold t :family "DejaVu_Sans_Mono" :foundry "apple" :width normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F8" :background "#1a1a1c" :stipple nil :weight bold :height 110))))
     (nxml-outline-indicator ((t (:family "DejaVu_Sans_Mono" :foundry "apple" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#F8F8F8" :background "#1a1a1c" :stipple nil :height 110))))
     (nxml-processing-instruction-content ((t (:foreground "#8F9D6A"))))
     (nxml-processing-instruction-delimiter ((t (nil))))
     (nxml-processing-instruction-target ((t (:foreground "#CDA869"))))
     (nxml-prolog-keyword ((t (:foreground "#CDA869"))))
     (nxml-prolog-literal-content ((t (:foreground "#8F9D6A"))))
     (nxml-prolog-literal-delimiter ((t (:foreground "#8F9D6A"))))
     (nxml-ref ((t (:foreground "#CF6A4C"))))
     (nxml-tag-delimiter ((t (nil))))
     (nxml-tag-slash ((t (nil))))
     (nxml-text ((t (nil))))
     (org-agenda-clocking ((t (:background "yellow1"))))
     (org-agenda-column-dateline ((t (:family "DejaVu_Sans_Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey90" :height 110))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-restriction-lock ((t (:background "yellow1"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red1"))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal :height 110 :family "DejaVu_Sans_Mono"))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:foreground "#9B703F"))))
     (org-level-2 ((t (:foreground "#7587A6"))))
     (org-level-3 ((t (:foreground "#CDA869"))))
     (org-level-4 ((t (:foreground "#5F5A60"))))
     (org-level-5 ((t (:foreground "#9B703F"))))
     (org-level-6 ((t (:foreground "#CF6A4C"))))
     (org-level-7 ((t (:foreground "#CACACA"))))
     (org-level-8 ((t (:foreground "#8F9D6A"))))
     (org-link ((t (:foreground "Purple" :underline t))))
     (org-meta-line ((t (:foreground "#5F5A60"))))
     (org-mode-default ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 120 :width normal :family "Monaco"))))
     (org-mode-line-clock ((t (:width normal :weight normal :slant normal :underline nil :strike-through nil :box (:line-width 3 :color "#0a0a0c") :foreground "#a0a0c0" :background "#0a0a0c" :stipple nil :strike-through nil :underline nil :family "Lucida Grande" :height 120))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:foreground "grey50"))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "RosyBrown"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-verse ((t (:foreground "grey50"))))
     (org-warning ((t (:foreground "red" :background "#EE799F"))))
     (outline-1 ((t (:foreground "#9B703F"))))
     (outline-2 ((t (:foreground "#7587A6"))))
     (outline-3 ((t (:foreground "#CDA869"))))
     (outline-4 ((t (:foreground "#5F5A60"))))
     (outline-5 ((t (:foreground "#9B703F"))))
     (outline-6 ((t (:foreground "#CF6A4C"))))
     (outline-7 ((t (:foreground "#CACACA"))))
     (outline-8 ((t (:foreground "#8F9D6A"))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "#27292A"))))
     (rng-error ((t (:foreground "red" :background "#EE799F"))))
     (rngalt-validation-header-bottom ((t (:background "RGB:87/CE/FA" :foreground "white"))))
     (rngalt-validation-header-top ((t (:background "white" :foreground "RGB:87/CE/FA"))))
     (scroll-bar ((t (nil))))
     (secondary-selection ((t (:background "yellow1"))))
     (sgml-namespace ((t (:foreground "#CACACA"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:bold t :foreground "#32CD32" :slant normal :weight bold))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:foreground "#CDA869"))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-face ((t (:background "#111111" :underline nil))))
     (slime-inspector-action-face ((t (:foreground "red" :background "#EE799F"))))
     (slime-inspector-label-face ((t (:foreground "#CF6A4C"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "#9B703F"))))
     (slime-inspector-value-face ((t (:foreground "#CACACA"))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:foreground "#5F5A60"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "#8F9D6A"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:foreground "#CDA869"))))
     (slime-repl-result-face ((t (:foreground "LightGreen"))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (swank-clojure-dim-trace-face ((t (:foreground "grey55"))))
     (text-cursor ((t (:background "yellow" :foreground "black"))))
     (text-mode-default ((t (:stipple nil :background "#1a1a1c" :foreground "#F8F8F8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :foundry "apple" :stipple nil :strike-through nil :underline nil :slant normal :weight normal :height 130 :width normal :family "Lucida Grande"))))
     (tool-bar ((t (nil))))
     (tooltip ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline nil))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (web-vcs-gold ((t (:background "gold" :foreground "black"))))
     (web-vcs-green ((t (:background "#8f6" :foreground "black"))))
     (web-vcs-mode-line ((t (:background "OrangeRed" :foreground "black"))))
     (web-vcs-mode-line-inactive ((t (:background "Orange" :foreground "black"))))
     (web-vcs-pink ((t (:background "pink" :foreground "black"))))
     (web-vcs-red ((t (:background "#f86" :foreground "black"))))
     (web-vcs-yellow ((t (:background "yellow" :foreground "black"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (zmacs-region ((t (:background "snow" :foreground "blue")))))))
(add-to-list 'color-themes '(color-theme-infinity  "@infinity+1" "Siddhartha Reddy"))

(provide 'color-theme-infinity)